import { Buffer } from "node:buffer";
import { randomBytes } from "node:crypto";

import { describe, expect, it } from "vitest";

import { extractVerificationCode } from "../src/backend/email.js";
import { generateIdentity } from "../src/backend/pseudonyms.js";
import {
  decryptJson,
  encryptJson,
  signInboundEmail,
  verifyInboundSignature
} from "../src/backend/security.js";
import { parseCreateReportInput } from "../src/backend/validation.js";

describe("backend identity and validation", () => {
  it("generates a localized unique German identity", () => {
    const identity = generateIdentity("de", "reports.example.org");
    expect(identity.country).toBe("DE");
    expect(identity.displayName).toContain(" ");
    expect(identity.internalReportId).toMatch(/^[a-z0-9-]+-[0-9a-hjkmnp-tv-z]{16}$/);
    expect(identity.email).toMatch(
      /^[a-z0-9.]+\.[0-9a-hjkmnp-tv-z]{16}@reports\.example\.org$/
    );
    expect(identity.timezone).toBe("Europe/Berlin");
  });

  it("rejects caller-supplied reporter identities", () => {
    expect(() =>
      parseCreateReportInput({
        country: "DE",
        flow: "message_urf",
        reportType: "sub_other_cybercrime",
        messageUrl: "https://discord.com/channels/1/2/3",
        legalName: "Caller supplied"
      })
    ).toThrow(/generated by the service/);
  });
});

describe("backend secrets and inbound email", () => {
  it("encrypts persisted secrets and authenticates raw email", () => {
    const key = randomBytes(32);
    const encrypted = encryptJson({ code: "ABC123" }, key);
    expect(encrypted).not.toContain("ABC123");
    expect(decryptJson<{ code: string }>(encrypted, key)).toEqual({ code: "ABC123" });

    const raw = Buffer.from("Subject: Discord code\r\n\r\nYour code is ABC123");
    const timestamp = "1800000000";
    const signature = signInboundEmail(
      "a".repeat(32),
      timestamp,
      "ticket.0123456789abcdef@example.org",
      "message-1",
      raw
    );
    expect(
      verifyInboundSignature({
        secret: "a".repeat(32),
        timestamp,
        recipient: "ticket.0123456789abcdef@example.org",
        messageId: "message-1",
        rawEmail: raw,
        signature,
        now: 1_800_000_000_000
      })
    ).toBe(true);
  });

  it("extracts one repeated Discord verification code", async () => {
    const raw = Buffer.from(
      "From: Discord <noreply@discord.com>\r\n" +
        "Subject: Your verification code is Z8RYMD\r\n" +
        "Content-Type: text/plain\r\n\r\nUse Z8RYMD to continue."
    );
    await expect(extractVerificationCode(raw)).resolves.toBe("Z8RYMD");
  });

  it("prefers the Discord subject key over CSS hexadecimal values", async () => {
    const raw = Buffer.from(
      "From: Discord <noreply@discord.com>\r\n" +
        "Subject: Your one-time verification key is ZX7KMH\r\n" +
        "Content-Type: multipart/alternative; boundary=discord-boundary\r\n\r\n" +
        "--discord-boundary\r\nContent-Type: text/plain\r\n\r\n" +
        "Your verification key is ZX7KMH.\r\n" +
        "--discord-boundary\r\nContent-Type: text/html\r\n\r\n" +
        "<style>.button{color:#2E3338;background:#4F5660}</style>" +
        "<p>Your verification key is <strong>ZX7KMH</strong>.</p>\r\n" +
        "--discord-boundary--"
    );
    await expect(extractVerificationCode(raw)).resolves.toBe("ZX7KMH");
  });

  it("does not treat ordinary six-letter words as verification codes", async () => {
    const raw = Buffer.from(
      "Subject: Please verify\r\nContent-Type: text/plain\r\n\r\nFollow normal instructions."
    );
    await expect(extractVerificationCode(raw)).resolves.toBeUndefined();
  });
});
