import { Buffer } from "node:buffer";
import { randomBytes } from "node:crypto";

import { describe, expect, it } from "vitest";

import {
  extractVerificationCode,
  parseDiscordEmail
} from "../src/backend/email.js";
import {
  buildAcceptLanguage,
  generateIdentity,
  supportedCountries
} from "../src/backend/pseudonyms.js";
import {
  decryptJson,
  encryptJson,
  signInboundEmail,
  verifyInboundSignature
} from "../src/backend/security.js";
import { parseCreateReportInput } from "../src/backend/validation.js";

describe("backend identity and validation", () => {
  it("generates a localized unique German identity", () => {
    const identity = generateIdentity("de", "reports.example.org");
    expect(identity.country).toBe("DE");
    expect(identity.displayName).toContain(" ");
    expect(identity.internalReportId).toMatch(/^[a-z0-9-]+-[0-9a-hjkmnp-tv-z]{16}$/);
    expect(identity.email).toMatch(
      /^[a-z0-9.]+\.[0-9a-hjkmnp-tv-z]{16}@reports\.example\.org$/
    );
    expect(identity.timezone).toBe("Europe/Berlin");
    expect(identity.locale).toBe("de-DE");
    expect(identity.language).toBe("de");
  });

  it("generates an internally consistent identity for every EU member state", () => {
    expect(supportedCountries()).toEqual([
      "AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "ES",
      "FI", "FR", "GR", "HR", "HU", "IE", "IT", "LT", "LU",
      "LV", "MT", "NL", "PL", "PT", "RO", "SE", "SI", "SK"
    ]);
    for (const country of supportedCountries()) {
      const identity = generateIdentity(country, "reports.example.org");
      expect(identity.country).toBe(country);
      expect(identity.displayName.trim().split(/\s+/).length).toBeGreaterThanOrEqual(2);
      expect(identity.internalReportId).toMatch(/^[a-z0-9-]+-[0-9a-hjkmnp-tv-z]{16}$/);
      expect(identity.email).toMatch(/^[a-z0-9.]+\.[0-9a-hjkmnp-tv-z]{16}@reports\.example\.org$/);
      expect(identity.locale).toMatch(/^[a-z]{2}-[A-Z]{2}$/);
      expect(identity.language).toMatch(/^[a-z]{2}$/);
      expect(identity.timezone).toContain("/");
      expect(buildAcceptLanguage(identity.locale, identity.language)).toContain(identity.locale);
    }
  });

  it("rejects caller-supplied reporter identities", () => {
    expect(() =>
      parseCreateReportInput({
        country: "DE",
        flow: "message_urf",
        reportType: "sub_other_cybercrime",
        messageUrl: "https://discord.com/channels/1/2/3",
        legalName: "Caller supplied"
      })
    ).toThrow(/generated by the service/);
  });
});

describe("backend secrets and inbound email", () => {
  it("encrypts persisted secrets and authenticates raw email", () => {
    const key = randomBytes(32);
    const encrypted = encryptJson({ code: "ABC123" }, key);
    expect(encrypted).not.toContain("ABC123");
    expect(decryptJson<{ code: string }>(encrypted, key)).toEqual({ code: "ABC123" });

    const raw = Buffer.from("Subject: Discord code\r\n\r\nYour code is ABC123");
    const timestamp = "1800000000";
    const signature = signInboundEmail(
      "a".repeat(32),
      timestamp,
      "ticket.0123456789abcdef@example.org",
      "message-1",
      raw
    );
    expect(
      verifyInboundSignature({
        secret: "a".repeat(32),
        timestamp,
        recipient: "ticket.0123456789abcdef@example.org",
        messageId: "message-1",
        rawEmail: raw,
        signature,
        now: 1_800_000_000_000
      })
    ).toBe(true);
  });

  it("extracts one repeated Discord verification code", async () => {
    const raw = Buffer.from(
      "From: Discord <noreply@discord.com>\r\n" +
        "Subject: Your verification code is Z8RYMD\r\n" +
        "Content-Type: text/plain\r\n\r\nUse Z8RYMD to continue."
    );
    await expect(extractVerificationCode(raw)).resolves.toBe("Z8RYMD");
  });

  it("prefers the Discord subject key over CSS hexadecimal values", async () => {
    const raw = Buffer.from(
      "From: Discord <noreply@discord.com>\r\n" +
        "Subject: Your one-time verification key is ZX7KMH\r\n" +
        "Content-Type: multipart/alternative; boundary=discord-boundary\r\n\r\n" +
        "--discord-boundary\r\nContent-Type: text/plain\r\n\r\n" +
        "Your verification key is ZX7KMH.\r\n" +
        "--discord-boundary\r\nContent-Type: text/html\r\n\r\n" +
        "<style>.button{color:#2E3338;background:#4F5660}</style>" +
        "<p>Your verification key is <strong>ZX7KMH</strong>.</p>\r\n" +
        "--discord-boundary--"
    );
    await expect(extractVerificationCode(raw)).resolves.toBe("ZX7KMH");
  });

  it("does not treat ordinary six-letter words as verification codes", async () => {
    const raw = Buffer.from(
      "Subject: Please verify\r\nContent-Type: text/plain\r\n\r\nFollow normal instructions."
    );
    await expect(extractVerificationCode(raw)).resolves.toBeUndefined();
  });

  it.each([
    {
      subject: "Report Received #1527695430949798110",
      text: "Your report reference number is #1527695430949798110.",
      status: "received"
    },
    {
      subject: "Report Actioned #1262026288437268564",
      text: "We reviewed your report and took action on the content.",
      status: "actioned"
    },
    {
      subject: "Report Closed #1527695430949798110",
      text: "We decided not to take action on the content in your report.",
      status: "closed_no_action"
    },
    {
      subject: "Report Closed #1450081430846574719",
      text: "We reviewed your report review request for report 1450081430846574719 and decided not to take action.",
      status: "review_not_approved"
    }
  ])("parses Discord lifecycle status $status", async ({ subject, text, status }) => {
    const reportId = subject.match(/\d{15,22}/)?.[0];
    const raw = Buffer.from(
      `From: Discord <noreply@discord.com>\r\nSubject: ${subject}\r\n` +
        `Content-Type: text/plain\r\n\r\n${text}`
    );
    await expect(parseDiscordEmail(raw)).resolves.toEqual({
      kind: "report_update",
      reportId,
      status
    });
  });
});
