import type { ReportDraft } from "@discord-dsa/client";
import type {
  GuildElement,
  ReportFlow,
  UserProfileElement
} from "@discord-dsa/contracts";
import { supportedCountries } from "./pseudonyms.js";

const FLOW_VALUES = new Set<ReportFlow>(["user_urf", "message_urf", "guild_urf"]);
export const DISCORD_FORM_LANGUAGE = "en" as const;
const PROFILE_ELEMENTS = new Set<UserProfileElement>(["photos", "name", "descriptors"]);
const GUILD_ELEMENTS = new Set<GuildElement>([
  "name",
  "icon",
  "banner",
  "invite_splash",
  "discovery_splash",
  "welcome_screen_description",
  "channel_names",
  "other"
]);

interface BaseCreateReportInput {
  country: string;
  flow: ReportFlow;
  reportType: string;
  submitterDiscordUserId?: string;
  context?: string;
  reporterUsername?: string;
}

export interface UserCreateReportInput extends BaseCreateReportInput {
  flow: "user_urf";
  reportedUsername: string;
  reportedUserServerId?: string;
  profileElements: UserProfileElement[];
}

export interface MessageCreateReportInput extends BaseCreateReportInput {
  flow: "message_urf";
  messageUrl: string;
}

export interface GuildCreateReportInput extends BaseCreateReportInput {
  flow: "guild_urf";
  guildIdOrInviteCode: string;
  guildElements: GuildElement[];
}

export type CreateReportInput =
  | UserCreateReportInput
  | MessageCreateReportInput
  | GuildCreateReportInput;

export interface RetryReportInput {
  submitterDiscordUserId: string;
}

function record(value: unknown): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error("Request body must be a JSON object.");
  }
  return value as Record<string, unknown>;
}

function requiredString(
  input: Record<string, unknown>,
  key: string,
  maximum = 2_000
): string {
  const value = input[key];
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`${key} must be a non-empty string.`);
  }
  const trimmed = value.trim();
  if (trimmed.length > maximum) throw new Error(`${key} is too long.`);
  return trimmed;
}

function optionalString(
  input: Record<string, unknown>,
  key: string,
  maximum: number
): string | undefined {
  if (input[key] === undefined) return undefined;
  return requiredString(input, key, maximum);
}

function stringArray<T extends string>(
  input: Record<string, unknown>,
  key: string,
  allowed: ReadonlySet<T>
): T[] {
  const value = input[key];
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error(`${key} must be a non-empty array.`);
  }
  const unique = new Set<T>();
  for (const item of value) {
    if (typeof item !== "string" || !allowed.has(item as T)) {
      throw new Error(`${key} contains an unsupported value.`);
    }
    unique.add(item as T);
  }
  return [...unique];
}

function rejectIdentityFields(input: Record<string, unknown>): void {
  for (const key of ["name", "legalName", "email", "reporterLegalName", "reporterEmail"]) {
    if (key in input) {
      throw new Error(`${key} is generated by the service and must not be supplied.`);
    }
  }
}

export function parseCreateReportInput(value: unknown): CreateReportInput {
  const input = record(value);
  rejectIdentityFields(input);
  const country = requiredString(input, "country", 2).toUpperCase();
  if (!supportedCountries().includes(country)) {
    throw new Error(`Unsupported country. Supported countries: ${supportedCountries().join(", ")}.`);
  }
  const flowValue = requiredString(input, "flow", 32);
  if (!FLOW_VALUES.has(flowValue as ReportFlow)) throw new Error("Unsupported flow.");
  const flow = flowValue as ReportFlow;
  const reportType = requiredString(input, "reportType", 100);
  if (!/^[a-z0-9_]+$/.test(reportType)) throw new Error("reportType is invalid.");
  const submitterDiscordUserId = optionalString(input, "submitterDiscordUserId", 22);
  if (
    submitterDiscordUserId !== undefined &&
    !/^\d{15,22}$/.test(submitterDiscordUserId)
  ) {
    throw new Error("submitterDiscordUserId must be a Discord snowflake.");
  }
  const context = optionalString(input, "context", 4_000);
  const reporterUsername = optionalString(input, "reporterUsername", 100);
  const base = {
    country,
    flow,
    reportType,
    ...(submitterDiscordUserId === undefined ? {} : { submitterDiscordUserId }),
    ...(context === undefined ? {} : { context }),
    ...(reporterUsername === undefined ? {} : { reporterUsername })
  };

  if (flow === "message_urf") {
    const messageUrl = requiredString(input, "messageUrl", 300);
    if (!/^https:\/\/(?:www\.)?discord\.com\/channels\/(?:@me|\d+)\/\d+\/\d+$/.test(messageUrl)) {
      throw new Error("messageUrl must be a complete Discord message URL.");
    }
    return { ...base, flow, messageUrl };
  }
  if (flow === "user_urf") {
    const reportedUsername = requiredString(input, "reportedUsername", 100);
    const reportedUserServerId = optionalString(input, "reportedUserServerId", 32);
    if (reportedUserServerId !== undefined && !/^\d{15,22}$/.test(reportedUserServerId)) {
      throw new Error("reportedUserServerId must be a Discord snowflake.");
    }
    return {
      ...base,
      flow,
      reportedUsername,
      ...(reportedUserServerId === undefined ? {} : { reportedUserServerId }),
      profileElements: stringArray(input, "profileElements", PROFILE_ELEMENTS)
    };
  }
  return {
    ...base,
    flow,
    guildIdOrInviteCode: requiredString(input, "guildIdOrInviteCode", 100),
    guildElements: stringArray(input, "guildElements", GUILD_ELEMENTS)
  };
}

export function parseRetryReportInput(value: unknown): RetryReportInput {
  const input = record(value);
  const submitterDiscordUserId = requiredString(input, "submitterDiscordUserId", 22);
  if (!/^\d{15,22}$/.test(submitterDiscordUserId)) {
    throw new Error("submitterDiscordUserId must be a Discord snowflake.");
  }
  return { submitterDiscordUserId };
}

export function toReportDraft(
  input: CreateReportInput,
  legalName: string
): ReportDraft {
  const reporter = {
    country: input.country,
    legalName,
    ...(input.reporterUsername === undefined ? {} : { username: input.reporterUsername })
  };
  const common = {
    reporter,
    reportType: input.reportType,
    ...(input.context === undefined ? {} : { context: input.context })
  };
  switch (input.flow) {
    case "message_urf":
      return { ...common, flow: input.flow, messageUrl: input.messageUrl };
    case "user_urf":
      return {
        ...common,
        flow: input.flow,
        reportedUsername: input.reportedUsername,
        ...(input.reportedUserServerId === undefined
          ? {}
          : { reportedUserServerId: input.reportedUserServerId }),
        profileElements: input.profileElements
      };
    case "guild_urf":
      return {
        ...common,
        flow: input.flow,
        guildIdOrInviteCode: input.guildIdOrInviteCode,
        guildElements: input.guildElements
      };
  }
}
