import { Buffer } from "node:buffer";
import { randomBytes } from "node:crypto";

import { describe, expect, it } from "vitest";

import {
  extractVerificationCode,
  inspectDiscordEmail,
  parseDiscordEmail
} from "../src/email.js";
import {
  isRetryableFailure,
  statusAfterSessionPersistence,
  shouldResendVerification,
  shouldApplyDiscordStatus,
  VERIFICATION_EMAIL_RESEND_DELAYS_SECONDS,
  VERIFICATION_EMAIL_TIMEOUT_SECONDS
} from "../src/database.js";
import {
  buildAcceptLanguage,
  generateEmailAlias,
  generateIdentity,
  supportedCountries
} from "../src/pseudonyms.js";
import {
  decryptJson,
  encryptJson,
  signInboundEmail,
  signReportEvent,
  verifyInboundSignature
} from "../src/security.js";
import {
  DISCORD_FORM_LANGUAGE,
  parseCreateReportInput,
  parseRetryReportInput
} from "../src/validation.js";

describe("backend identity and validation", () => {
  it("keeps Discord's form language independent from the country locale", () => {
    const identity = generateIdentity("DE", "reports.example.org");

    expect(identity.language).toBe("de");
    expect(DISCORD_FORM_LANGUAGE).toBe("en");
  });

  it("generates a localized unique German identity", () => {
    const identity = generateIdentity("de", "reports.example.org");
    expect(identity.country).toBe("DE");
    expect(identity.displayName).toContain(" ");
    expect(identity.internalReportId).toMatch(/^[a-z0-9-]+-[0-9a-hjkmnp-tv-z]{16}$/);
    expect(identity.email).toMatch(
      /^[a-z0-9.]+\.[0-9a-hjkmnp-tv-z]{16}@reports\.example\.org$/
    );
    expect(identity.timezone).toBe("Europe/Berlin");
    expect(identity.locale).toBe("de-DE");
    expect(identity.language).toBe("de");
  });

  it("generates an internally consistent identity for every EU member state", () => {
    expect(supportedCountries()).toEqual([
      "AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "ES",
      "FI", "FR", "GR", "HR", "HU", "IE", "IT", "LT", "LU",
      "LV", "MT", "NL", "PL", "PT", "RO", "SE", "SI", "SK"
    ]);
    for (const country of supportedCountries()) {
      const identity = generateIdentity(country, "reports.example.org");
      expect(identity.country).toBe(country);
      expect(identity.displayName.trim().split(/\s+/).length).toBeGreaterThanOrEqual(2);
      expect(identity.internalReportId).toMatch(/^[a-z0-9-]+-[0-9a-hjkmnp-tv-z]{16}$/);
      expect(identity.email).toMatch(/^[a-z0-9.]+\.[0-9a-hjkmnp-tv-z]{16}@reports\.example\.org$/);
      expect(identity.locale).toMatch(/^[a-z]{2}-[A-Z]{2}$/);
      expect(identity.language).toMatch(/^[a-z]{2}$/);
      expect(identity.timezone).toContain("/");
      expect(buildAcceptLanguage(identity.locale, identity.language)).toContain(identity.locale);
    }
  });

  it.each(["BG", "EE", "LT", "MT"])(
    "uses Faker's generic English name fallback for %s",
    (country) => {
      for (let sample = 0; sample < 10; sample += 1) {
        expect(generateIdentity(country, "reports.example.org").displayName).toMatch(
          /^[\x20-\x7E]+$/
        );
      }
    }
  );

  it("rejects caller-supplied reporter identities", () => {
    expect(() =>
      parseCreateReportInput({
        country: "DE",
        flow: "message_urf",
        reportType: "sub_other_cybercrime",
        messageUrl: "https://discord.com/channels/1/2/3",
        legalName: "Caller supplied"
      })
    ).toThrow(/generated by the service/);
  });

  it("accepts and validates internal Discord submitter ownership", () => {
    const input = parseCreateReportInput({
      country: "DE",
      flow: "message_urf",
      reportType: "sub_other_hate_speech",
      messageUrl: "https://discord.com/channels/427067963137589258/427069953078853633/1414818522701369355",
      submitterDiscordUserId: "1057381507204915281"
    });
    expect(input.submitterDiscordUserId).toBe("1057381507204915281");
    expect(() =>
      parseCreateReportInput({
        country: "DE",
        flow: "message_urf",
        reportType: "sub_other_hate_speech",
        messageUrl: "https://discord.com/channels/1/2/3",
        submitterDiscordUserId: "not-a-user"
      })
    ).toThrow(/Discord snowflake/);
  });

  it("accepts a validated resolved-user snapshot without requiring a schema migration", () => {
    const input = parseCreateReportInput({
      country: "DE",
      flow: "user_urf",
      reportType: "sub_other_hate_speech",
      reportedUsername: "example",
      reportedUserId: "123456789012345678",
      reportedUserSnapshot: {
        userId: "123456789012345678",
        username: "example",
        globalDisplayName: "Example Display",
        avatarUrl: "https://cdn.discordapp.com/avatar.png",
        bot: false,
        resolvedAt: "2026-07-20T00:00:00.000Z"
      },
      profileElements: ["name"]
    });
    expect(input).toMatchObject({
      reportedUserId: "123456789012345678",
      reportedUsername: "example"
    });
    expect(() =>
      parseCreateReportInput({
        ...input,
        reportedUserId: "223456789012345678"
      })
    ).toThrow(/must match reportedUserId/);
  });

  it("rotates the email alias without changing the pseudonym", () => {
    const identity = generateIdentity("DE", "reports.example.org");
    const retryEmail = generateEmailAlias(
      identity.displayName,
      identity.language,
      "reports.example.org"
    );
    expect(retryEmail).not.toBe(identity.email);
    expect(retryEmail).toMatch(
      /^[a-z0-9.]+\.[0-9a-hjkmnp-tv-z]{16}@reports\.example\.org$/
    );
  });

  it("validates retry ownership and blocks unsafe failure stages", () => {
    expect(VERIFICATION_EMAIL_TIMEOUT_SECONDS).toBe(60);
    expect(
      parseRetryReportInput({ submitterDiscordUserId: "1197857362942378017" })
    ).toEqual({ submitterDiscordUserId: "1197857362942378017" });
    expect(() =>
      parseRetryReportInput({ submitterDiscordUserId: "invalid" })
    ).toThrow(/Discord snowflake/);
    expect(
      isRetryableFailure("requesting_verification", "report_processing_failed", 1)
    ).toBe(true);
    expect(isRetryableFailure("awaiting_verification", "verification_email_timeout", 0)).toBe(
      true
    );
    expect(isRetryableFailure("submitting", "report_processing_failed", 1)).toBe(false);
    expect(isRetryableFailure("verifying", "ambiguous_submission_state", 1)).toBe(false);
    expect(isRetryableFailure("verifying", "report_processing_failed", 2)).toBe(false);
  });

  it("preserves an email that arrives before session persistence completes", () => {
    expect(statusAfterSessionPersistence("requesting_verification")).toBe(
      "awaiting_verification"
    );
    expect(statusAfterSessionPersistence("verification_received")).toBe(
      "verification_received"
    );
  });

  it("resends only inside the fixed verification window", () => {
    expect(VERIFICATION_EMAIL_RESEND_DELAYS_SECONDS).toEqual([20, 40]);
    const deadline = new Date("2026-07-20T12:01:00.000Z");
    expect(
      shouldResendVerification(
        { status: "awaiting_verification", session_state: "encrypted", verification_deadline: deadline },
        new Date("2026-07-20T12:00:40.000Z")
      )
    ).toBe(true);
    expect(
      shouldResendVerification(
        { status: "verification_received", session_state: "encrypted", verification_deadline: null },
        new Date("2026-07-20T12:00:40.000Z")
      )
    ).toBe(false);
    expect(
      shouldResendVerification(
        { status: "awaiting_verification", session_state: "encrypted", verification_deadline: deadline },
        deadline
      )
    ).toBe(false);
  });
});

describe("backend secrets and inbound email", () => {
  it("suppresses duplicate and out-of-order Discord status updates", () => {
    expect(shouldApplyDiscordStatus(null, "received")).toBe(true);
    expect(shouldApplyDiscordStatus("received", "received")).toBe(false);
    expect(shouldApplyDiscordStatus("received", "actioned")).toBe(true);
    expect(shouldApplyDiscordStatus("actioned", "received")).toBe(false);
    expect(shouldApplyDiscordStatus("closed_no_action", "actioned")).toBe(false);
  });

  it("encrypts persisted secrets and authenticates raw email", () => {
    const key = randomBytes(32);
    const encrypted = encryptJson({ code: "ABC123" }, key);
    expect(encrypted).not.toContain("ABC123");
    expect(decryptJson<{ code: string }>(encrypted, key)).toEqual({ code: "ABC123" });

    const raw = Buffer.from("Subject: Discord code\r\n\r\nYour code is ABC123");
    const timestamp = "1800000000";
    const signature = signInboundEmail(
      "a".repeat(32),
      timestamp,
      "ticket.0123456789abcdef@example.org",
      "message-1",
      raw
    );
    expect(
      verifyInboundSignature({
        secret: "a".repeat(32),
        timestamp,
        recipient: "ticket.0123456789abcdef@example.org",
        messageId: "message-1",
        rawEmail: raw,
        signature,
        now: 1_800_000_000_000
      })
    ).toBe(true);
  });

  it("signs lifecycle webhook payloads deterministically", () => {
    const signature = signReportEvent("s".repeat(32), "1800000000", "42", "{\"eventId\":\"42\"}");
    expect(signature).toMatch(/^[a-f0-9]{64}$/);
    expect(signature).toBe(
      signReportEvent("s".repeat(32), "1800000000", "42", "{\"eventId\":\"42\"}")
    );
  });

  it("extracts one repeated Discord verification code", async () => {
    const raw = Buffer.from(
      "From: Discord <noreply@discord.com>\r\n" +
        "Subject: Your verification code is Z8RYMD\r\n" +
        "Content-Type: text/plain\r\n\r\nUse Z8RYMD to continue."
    );
    await expect(extractVerificationCode(raw)).resolves.toBe("Z8RYMD");
  });

  it("prefers the Discord subject key over CSS hexadecimal values", async () => {
    const raw = Buffer.from(
      "From: Discord <noreply@discord.com>\r\n" +
        "Subject: Your one-time verification key is ZX7KMH\r\n" +
        "Content-Type: multipart/alternative; boundary=discord-boundary\r\n\r\n" +
        "--discord-boundary\r\nContent-Type: text/plain\r\n\r\n" +
        "Your verification key is ZX7KMH.\r\n" +
        "--discord-boundary\r\nContent-Type: text/html\r\n\r\n" +
        "<style>.button{color:#2E3338;background:#4F5660}</style>" +
        "<p>Your verification key is <strong>ZX7KMH</strong>.</p>\r\n" +
        "--discord-boundary--"
    );
    await expect(extractVerificationCode(raw)).resolves.toBe("ZX7KMH");
  });

  it("extracts a letter-only Discord verification key from the exact subject", async () => {
    const raw = Buffer.from(
      "From: Discord <noreply@discord.com>\r\n" +
        "Subject: Your one-time verification key is STLGSY\r\n" +
        "Content-Type: text/plain\r\n\r\nYour verification key is STLGSY."
    );
    await expect(extractVerificationCode(raw)).resolves.toBe("STLGSY");
  });

  it("uses a contextual body phrase when the subject has no code", async () => {
    const raw = Buffer.from(
      "From: Discord <noreply@discord.com>\r\n" +
        "Subject: Verify your report\r\n" +
        "Content-Type: text/plain\r\n\r\nYour verification code is ab12cd."
    );
    await expect(extractVerificationCode(raw)).resolves.toBe("AB12CD");
  });

  it("does not treat ordinary six-letter words as verification codes", async () => {
    const raw = Buffer.from(
      "Subject: Please verify\r\nContent-Type: text/plain\r\n\r\nFollow normal instructions."
    );
    await expect(extractVerificationCode(raw)).resolves.toBeUndefined();
  });

  it("classifies and sanitizes an unmatched Discord lifecycle email", async () => {
    const raw = Buffer.from(
      "From: Discord <noreply@discord.com>\r\n" +
        "Subject: Discord report received: #1527695430949798110\r\n" +
        "Content-Type: text/plain\r\n\r\n" +
        "Reference ABC123 was sent to reporter@example.org."
    );
    await expect(inspectDiscordEmail(raw)).resolves.toEqual({
      kind: "ignored",
      diagnostic: {
        classification: "discord_lifecycle_subject_unmatched",
        senderAddresses: ["noreply@discord.com"],
        subject: "Discord report received: #1527695430949798110",
        textPreview: "Reference [redacted-code] was sent to [redacted-email]."
      }
    });
  });

  it("classifies a non-Discord sender without exposing body email addresses", async () => {
    const raw = Buffer.from(
      "From: Example <alerts@example.org>\r\n" +
        "Subject: Verify your report\r\n" +
        "Content-Type: text/plain\r\n\r\nContact private@example.org."
    );
    await expect(inspectDiscordEmail(raw)).resolves.toMatchObject({
      kind: "ignored",
      diagnostic: {
        classification: "non_discord_sender",
        senderAddresses: ["alerts@example.org"],
        textPreview: "Contact [redacted-email]."
      }
    });
  });

  it.each([
    {
      subject: "Report Received #1527695430949798110",
      text: "Your report reference number is #1527695430949798110.",
      status: "received"
    },
    {
      subject: "Report Actioned #1262026288437268564",
      text: "We reviewed your report and took action on the content.",
      status: "actioned"
    },
    {
      subject: "Report Closed #1527695430949798110",
      text: "We decided not to take action on the content in your report.",
      status: "closed_no_action"
    },
    {
      subject: "Report Closed #1450081430846574719",
      text: "We reviewed your report review request for report 1450081430846574719 and decided not to take action.",
      status: "review_not_approved"
    }
  ])("parses Discord lifecycle status $status", async ({ subject, text, status }) => {
    const reportId = subject.match(/\d{15,22}/)?.[0];
    const raw = Buffer.from(
      `From: Discord <noreply@discord.com>\r\nSubject: ${subject}\r\n` +
        `Content-Type: text/plain\r\n\r\n${text}`
    );
    await expect(parseDiscordEmail(raw)).resolves.toEqual({
      kind: "report_update",
      reportId,
      status
    });
  });
});
